sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mzaghi/docker-react-pipeline -f Dockerfile.dev .

script:
  - docker run -e CI=true mzaghi/docker-react-pipeline npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-433287836791"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY